services:
  - type: docker
    name: wordpress
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password

databases:
  - name: wordpress-db
    plan: starter
    ipAllowList: []
