services:
  - type: web
    name: wordpress
    env: docker
    image: wordpress:latest
    plan: starter
    port: 80
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
    disk:
      name: wp-content
      mountPath: /var/www/html/wp-content
      sizeGB: 1

databases:
  - name: wordpress-db
    plan: starter
    databaseName: wordpress
    user: wordpress
